# Generated by Django 3.2.10 on 2022-01-05 14:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuotteet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvostelu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahdet', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('teksti', models.TextField(blank=True, max_length=500)),
                ('arvostelija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arvostelija', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tuote',
            name='arvostelut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuotteet.arvostelu'),
        ),
    ]
