# Generated by Django 3.2.10 on 2022-01-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0002_auto_20220105_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuote',
            old_name='arvostelut',
            new_name='arvostelu',
        ),
    ]
