# Generated by Django 3.2.10 on 2022-01-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0003_rename_arvostelut_tuote_arvostelu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='arvostelu',
        ),
    ]
