# Generated by Django 3.2.10 on 2022-01-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0004_remove_tuote_arvostelu'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvostelu',
            name='tuote_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuotteet.tuote'),
        ),
    ]
